# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18uG8tHdXgvHw_UMnQKEkq_ixkQo8rBnd
"""

import pandas as pd
import numpy as np
import datetime

"""ZADANIE 1"""

PATH = './drive/MyDrive'
df = pd.read_csv(f'{PATH}/orders.csv')
df['order_date'] = pd.to_datetime(df['order_date']).dt.date
df.info()

print(df['tshirt_category'].unique())
liczba_kategorii = len(df['tshirt_category'].unique())
print(f'Liczba kategorii -- {liczba_kategorii}')

df['tshirt_category'] = df['tshirt_category'].astype('string')
df['tshirt_category'] = df['tshirt_category'].apply(lambda x: x.replace('Wh ', 'White ').replace('Bl ', 'Black ').replace('Tshirt ', 'T-Shirt ').replace('Hoodie','Other Hoodie Other').replace(' Shirt', ' Shirt Other'))
print(df['tshirt_category'].unique())

df['tshirt_colour'] = df['tshirt_category'].apply(lambda x: x.split(' ')[0])
df['tshirt_type'] = df['tshirt_category'].apply(lambda x: x.split(' ')[1])
df['tshirt_sex'] = df['tshirt_category'].apply(lambda x: x.split(' ')[2])
df

a = df[(df['order_date'] > datetime.date(2014,12,31)) & (df['order_date'] < datetime.date(2016,8,2))].sort_values('order_date')
a



"""ZADANIE 2"""

print(f'Wymiary ramki z pierwszego zadania {df.shape}')
df2 = pd.read_csv(f'{PATH}/customers.csv')
print(f'Wymiary ramki z drugiego zadania {df2.shape}')

df2.info()

print(df_2.columns)

df_2.rename(columns = {'customerID':'customer_ID'}, inplace=True)
df_2.columns

pd.merge(df, df_2, how='inner', left_on='customer_id', right_on='customer_ID')

result = pd.merge(df, df_2, how='inner', left_on='customer_id', right_on='customer_ID')
result.drop(['customer_id'], axis=1)
result.to_csv('result.csv',index=False)

"""niestety pojawił się jakiś problem z plikiem customers.csv, więc nie zamieszczam rezulatatów, poniewaz pokazuje ciągle błąd. Jesli rozwiąże ten problem to wstawię rozwiązania z rezultatami."""