# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gOgwy1WIdjMYit329rBbMDihApkNPgJN

Zadanie 1
"""

import pandas as pd

PATH = './drive/MyDrive'
hw = pd.read_csv(f'{PATH}/PAD_03_PD.csv', sep = ';')
hw

hw.groupby('Country').count()

"""Zadanie 2"""

hw['owned_goods'] = hw.owns_car + hw.owns_TV + hw.owns_house + hw.owns_Phone
hw

"""Zadanie 3"""

hw.groupby('gender').mean().owned_goods.round(2)

"""Zadanie 4"""

